#!/usr/bin/bash

# create 2 folders named 'modules' and 'headers' and 1 file named "main.cpp" in the working directory from where this script is executed

# script for personal use, I use it for modularity in my own projects
mkdir ${pwd}modules
mkdir ${pwd}headers
touch ${pwd}main.cpp